/*
 * THIS IS A GENERATED FILE. DO NOT EDIT !!!
*/
export const EnumDEV = {
    "ENERGY__VCAP": "ENERGY__VCAP",
    "ENERGY__LOWLIGHT": "ENERGY__LOWLIGHT",
    "ALERT__TRIGGERED": "ALERT__TRIGGERED",
    "ALERT__ARMED": "ALERT__ARMED",
    "POSITION__LATITUDE": "POSITION__LATITUDE",
    "POSITION__LONGITUDE": "POSITION__LONGITUDE"
}

export const EnumENERGY = {
    "VCAP": "VCAP",
    "LOWLIGHT": "LOWLIGHT"
}
export const EnumALERT = {
    "TRIGGERED": "TRIGGERED",
    "ARMED": "ARMED"
}
export const EnumPOSITION = {
    "LATITUDE": "LATITUDE",
    "LONGITUDE": "LONGITUDE"
}