/*
 * THIS IS A GENERATED FILE. DO NOT EDIT !!!
*/
export const EnumMODEL = {
    "NUM__ENV__ATMO__SNOW__HEIGHT__SNOW_MAUS": "NUM__ENV__ATMO__SNOW__HEIGHT__SNOW_MAUS",
    "NUM__ENV__ATMO__SNOW__INSULATION__SNOW_MAUS": "NUM__ENV__ATMO__SNOW__INSULATION__SNOW_MAUS",
    "NUM__ENV__ATMO__SNOW__MELT__SNOW_MAUS": "NUM__ENV__ATMO__SNOW__MELT__SNOW_MAUS"
}

export const EnumNUM = {
    "ENV__ATMO__SNOW__HEIGHT__SNOW_MAUS": "ENV__ATMO__SNOW__HEIGHT__SNOW_MAUS",
    "ENV__ATMO__SNOW__INSULATION__SNOW_MAUS": "ENV__ATMO__SNOW__INSULATION__SNOW_MAUS",
    "ENV__ATMO__SNOW__MELT__SNOW_MAUS": "ENV__ATMO__SNOW__MELT__SNOW_MAUS"
}