/*
 * THIS IS A GENERATED FILE. DO NOT EDIT !!!
*/
export const EnumMODEL = {
    "NUM__ENV__ATMO__SNOW__HEIGHT": "NUM__ENV__ATMO__SNOW__HEIGHT",
    "NUM__ENV__ATMO__SNOW__MELT": "NUM__ENV__ATMO__SNOW__MELT",
    "NUM__ENV__ATMO__SNOW__INSULATION": "NUM__ENV__ATMO__SNOW__INSULATION"
}

export const EnumNUM = {
    "ENV__ATMO__SNOW__HEIGHT": "ENV__ATMO__SNOW__HEIGHT",
    "ENV__ATMO__SNOW__MELT": "ENV__ATMO__SNOW__MELT",
    "ENV__ATMO__SNOW__INSULATION": "ENV__ATMO__SNOW__INSULATION"
}