/*
 * THIS IS A GENERATED FILE. DO NOT EDIT !!!
 */
import { registerEnumType } from "type-graphql";
export const MeasurableParameterNames = {
    ENV__ATMO__T: "ENV__ATMO__T",
    ENV__ATMO__P: "ENV__ATMO__P",
    ENV__ATMO__RH: "ENV__ATMO__RH",
    ENV__ATMO__IRRADIATION: "ENV__ATMO__IRRADIATION",
    ENV__ATMO__WIND__SPEED: "ENV__ATMO__WIND__SPEED",
    ENV__ATMO__WIND__GUSTINESS: "ENV__ATMO__WIND__GUSTINESS",
    ENV__ATMO__WIND__DIRECTION: "ENV__ATMO__WIND__DIRECTION",
    ENV__ATMO__SNOW__HEIGHT: "ENV__ATMO__SNOW__HEIGHT",
    ENV__ATMO__SNOW__INSULATION: "ENV__ATMO__SNOW__INSULATION",
    ENV__ATMO__SNOW__MELT: "ENV__ATMO__SNOW__MELT",
    ENV__SOIL__T: "ENV__SOIL__T",
    ENV__SOIL__EC: "ENV__SOIL__EC",
    ENV__SOIL__NORM_ER: "ENV__SOIL__NORM_ER",
    ENV__SOIL__VWC: "ENV__SOIL__VWC",
    ENV__SOIL__MATRIX_POTENTIAL: "ENV__SOIL__MATRIX_POTENTIAL",
    DEV__LIQUIDLEVEL: "DEV__LIQUIDLEVEL",
    DEV__WEIGHT: "DEV__WEIGHT",
    MODEL__ENV__ATMO__SNOW__HEIGHT: "MODEL__ENV__ATMO__SNOW__HEIGHT",
    MODEL__ENV__ATMO__SNOW__MELT: "MODEL__ENV__ATMO__SNOW__MELT",
    MODEL__ENV__ATMO__SNOW__INSULATION: "MODEL__ENV__ATMO__SNOW__INSULATION",
};
registerEnumType(MeasurableParameterNames, {
    name: "MeasurableParameterNames",
});
