/*
 * THIS IS A GENERATED FILE. DO NOT EDIT !!!
 */
import { registerEnumType } from "type-graphql";
export const MeasurableParameterNames = {
    ENV__ATMO__T: "ENV__ATMO__T",
    ENV__ATMO__P: "ENV__ATMO__P",
    ENV__ATMO__RH: "ENV__ATMO__RH",
    ENV__ATMO__IRRADIATION: "ENV__ATMO__IRRADIATION",
    ENV__ATMO__WIND__SPD__AVG: "ENV__ATMO__WIND__SPD__AVG",
    ENV__ATMO__WIND__SPD__STD: "ENV__ATMO__WIND__SPD__STD",
    ENV__ATMO__WIND__DIR: "ENV__ATMO__WIND__DIR",
    DEV__ENERGY__LATITUDE: "DEV__ENERGY__LATITUDE",
    DEV__ENERGY__LONGITUDE: "DEV__ENERGY__LONGITUDE",
    DEV__ALERT__TRIGGERED: "DEV__ALERT__TRIGGERED",
    DEV__ALERT__ARMED: "DEV__ALERT__ARMED",
    MODEL__ENV__ATMO__SNOW__HEIGHT: "MODEL__ENV__ATMO__SNOW__HEIGHT",
    MODEL__ENV__ATMO__SNOW__MELT: "MODEL__ENV__ATMO__SNOW__MELT",
    MODEL__ENV__ATMO__SNOW__INSULATION: "MODEL__ENV__ATMO__SNOW__INSULATION",
};
registerEnumType(MeasurableParameterNames, {
    name: "MeasurableParameterNames",
});
